# Generated by Django 5.0.4 on 2026-04-11 11:35

import core.utils.files
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("user", "User"), ("staff", "Staff")],
                        db_index=True,
                        default="user",
                        max_length=10,
                    ),
                ),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        upload_to=core.utils.files.SmartUploadPath(
                            core.utils.files.UploadPathConfig(
                                base_path="profile_pictures",
                                field_lookup="user.id",
                                filename_mode="prepend_uuid",
                            )
                        ),
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientAccountSuspension",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("policy_violation", "Policy Violation"),
                            ("abusive_behavior", "Abusive Behavior"),
                            ("spam", "Spam"),
                            ("fraud", "Fraud"),
                            ("payment_issue", "Payment Issue"),
                            ("under_review", "Under Review"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Primary reason for the suspension.",
                        max_length=50,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Additional context or notes about the suspension.",
                    ),
                ),
                (
                    "suspended_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the suspension was created."
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the suspension automatically expires. Leave blank for indefinite.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("lifted", "Lifted"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Current state of the suspension. Managed automatically.",
                        max_length=20,
                    ),
                ),
                (
                    "lifted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the suspension was manually lifted.",
                        null=True,
                    ),
                ),
                (
                    "lift_reason",
                    models.TextField(
                        blank=True, help_text="Reason for lifting the suspension early."
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The client being suspended.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspensions",
                        to="users.client",
                    ),
                ),
                (
                    "lifted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who manually lifted the suspension.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspensions_lifted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suspended_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who applied the suspension.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspensions_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Suspension",
                "verbose_name_plural": "Account Suspensions",
                "ordering": ["-suspended_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientBanRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason_to_ban", models.TextField()),
                ("reason_to_unban", models.TextField(blank=True)),
                ("banned_at", models.DateTimeField(auto_now_add=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ban_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("temporary", "Temporary"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ban_records",
                        to="users.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("device_id", models.CharField(db_index=True, max_length=255)),
                ("device_type", models.CharField(max_length=50)),
                ("device_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_used_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="users.client",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["user"], name="users_clien_user_id_db03ad_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["full_name"], name="users_clien_full_na_012fd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientaccountsuspension",
            index=models.Index(
                fields=["client", "status"], name="users_clien_client__c5feed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientaccountsuspension",
            index=models.Index(
                fields=["status", "ends_at"], name="users_clien_status_6bd1af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientaccountsuspension",
            index=models.Index(
                fields=["suspended_by"], name="users_clien_suspend_c3a896_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientbanrecord",
            index=models.Index(
                fields=["client"], name="users_clien_client__ecfd6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientbanrecord",
            index=models.Index(
                fields=["is_active", "ban_type", "end_at"],
                name="users_clien_is_acti_7d81ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clientdevice",
            index=models.Index(
                fields=["client", "device_id"], name="users_clien_client__19bd95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientdevice",
            index=models.Index(
                fields=["is_active"], name="users_clien_is_acti_75eb10_idx"
            ),
        ),
    ]
