# Generated by Django 5.0.4 on 2026-04-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auth_hardening"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="authsession",
            new_name="users_auths_user_id_3e09e8_idx",
            old_name="users_auths_user_id_9f0675_idx",
        ),
        migrations.RenameIndex(
            model_name="authsession",
            new_name="users_auths_user_id_c6623e_idx",
            old_name="users_auths_user_id_22f6ba_idx",
        ),
        migrations.RenameIndex(
            model_name="authsession",
            new_name="users_auths_session_d799e7_idx",
            old_name="users_auths_session_13bf5f_idx",
        ),
        migrations.RenameIndex(
            model_name="authsession",
            new_name="users_auths_access__658a62_idx",
            old_name="users_auths_access__8d4f5e_idx",
        ),
        migrations.RenameIndex(
            model_name="clientdevice",
            new_name="users_clien_client__fab851_idx",
            old_name="users_clien_client__680f4e_idx",
        ),
        migrations.RenameIndex(
            model_name="tokenblacklist",
            new_name="users_token_jti_45c947_idx",
            old_name="users_token_jti_2e7b77_idx",
        ),
        migrations.AddField(
            model_name="client",
            name="is_two_factor_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
