# Generated by Django 5.0.4 on 2026-04-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_authsession_city_authsession_country_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authsession",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="authsession",
            name="country_code",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
