# Generated by Django 5.0.4 on 2026-04-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_client_backup_codes_client_totp_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='TokenBlacklist',
        ),
        migrations.DeleteModel(
            name='AuthSession',
        ),
    ]
