# Generated by Django 5.0.4 on 2026-05-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_client_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_email_masked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='masked_email',
            field=models.EmailField(blank=True, db_index=True, editable=False, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.SlugField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['username'], name='users_clien_usernam_621868_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['masked_email'], name='users_clien_masked__499abc_idx'),
        ),
    ]
