# Generated by Django 5.0.4 on 2026-05-02 05:13

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_client_is_email_masked_client_masked_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_username_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.SlugField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
