# Generated by Django 5.0.4 on 2026-05-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_client_last_username_change_alter_client_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='last_username_change',
        ),
        migrations.AddField(
            model_name='client',
            name='username_change_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
