# Generated by Django 5.0.4 on 2026-05-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_client_last_username_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='who_can_add_me',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('contacts', 'Contacts Only'), ('request', 'Request Required')], default='everyone', max_length=20),
        ),
    ]
