# Generated by Django 5.0.4 on 2026-05-02 05:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_client_who_can_add_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, help_text='Custom name given to this contact by the owner.', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_user', models.ForeignKey(help_text='The user being added as a contact.', on_delete=django.db.models.deletion.CASCADE, related_name='contacted_by', to='users.client')),
                ('owner', models.ForeignKey(help_text='The user who owns this contact entry.', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='users.client')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'indexes': [models.Index(fields=['owner', 'status'], name='users_conta_owner_i_968e61_idx'), models.Index(fields=['contact_user', 'status'], name='users_conta_contact_732352_idx')],
                'unique_together': {('owner', 'contact_user')},
            },
        ),
    ]
