# Generated by Django 5.0.4 on 2026-05-02 06:34

import core.utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='banner_picture',
            field=models.ImageField(blank=True, upload_to=core.utils.files.SmartUploadPath(core.utils.files.UploadPathConfig(base_path='banner_pictures', field_lookup='user.id', filename_mode='prepend_uuid'))),
        ),
    ]
