# Generated by Django 5.0.4 on 2026-04-19 10:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenBlacklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jti', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['jti', 'expires_at'], name='authenticat_jti_90d109_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('client', 'Client'), ('staff', 'Staff')], db_index=True, default='client', max_length=20)),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('access_jti', models.CharField(db_index=True, max_length=64)),
                ('refresh_jti', models.CharField(db_index=True, max_length=64, unique=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('device_label', models.CharField(max_length=255)),
                ('device_entropy', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country_code', models.CharField(blank=True, default='', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='authenticat_user_id_9bc38a_idx'), models.Index(fields=['user', 'expires_at'], name='authenticat_user_id_1f6ded_idx'), models.Index(fields=['session_id', 'user'], name='authenticat_session_b1c0fe_idx'), models.Index(fields=['access_jti', 'user'], name='authenticat_access__216884_idx')],
            },
        ),
    ]
