# Generated by Django 5.0.4 on 2026-05-02 09:18

import core.utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.files.SmartUploadPath(core.utils.files.UploadPathConfig(base_path='room_avatars', field_lookup='id', filename_mode='prepend_uuid'))),
        ),
        migrations.AddField(
            model_name='room',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.files.SmartUploadPath(core.utils.files.UploadPathConfig(base_path='room_banners', field_lookup='id', filename_mode='prepend_uuid'))),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
