# Generated by Django 5.0.4 on 2026-05-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_avatar_room_banner_room_description'),
        ('users', '0014_client_banner_picture'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='messagereceipt',
            name='chat_messag_client__362745_idx',
        ),
        migrations.RemoveIndex(
            model_name='roommembership',
            name='chat_room_m_client__c8c5e6_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('FILE', 'File'), ('SYSTEM', 'System')], default='TEXT', max_length=10),
        ),
        migrations.AddField(
            model_name='roommembership',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roommembership',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roommembership',
            name='unread_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='messagereceipt',
            index=models.Index(fields=['client', 'status', 'message'], name='chat_messag_client__583f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereceipt',
            index=models.Index(fields=['message', 'status'], name='chat_messag_message_abe2c0_idx'),
        ),
        migrations.AddIndex(
            model_name='roommembership',
            index=models.Index(fields=['client', 'is_active', 'unread_count'], name='chat_room_m_client__b4d53d_idx'),
        ),
    ]
