# Generated by Django 5.0.4 on 2026-05-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_messagereceipt_chat_messag_client__362745_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sequence_id',
            field=models.BigIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
