# Generated by Django 5.0.4 on 2026-05-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_sequence_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
