# Generated by Django 5.0.4 on 2026-05-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_idempotency_key'),
        ('users', '0014_client_banner_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sequence_id'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_room_id_584819_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='sent_at',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', '-sent_at'], name='chat_messag_room_id_915627_idx'),
        ),
    ]
