# Generated by Django 5.0.4 on 2026-05-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_backfill_direct_room_slugs'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['slug', 'is_deleted'], name='chat_rooms_slug_c27769_idx'),
        ),
    ]
