# Generated by Django 5.0.4 on 2026-05-06 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_delivered_at_message_edited_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('FILE', 'File')], max_length=20)),
                ('storage_key', models.CharField(max_length=1024)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message')),
            ],
            options={
                'verbose_name': 'Message Attachment',
                'verbose_name_plural': 'Message Attachments',
                'db_table': 'chat_message_attachments',
                'indexes': [models.Index(fields=['message', 'type'], name='chat_messag_message_05baf4_idx'), models.Index(fields=['storage_key'], name='chat_messag_storage_6016c4_idx')],
            },
        ),
    ]
